title: Jiwon Kang
url: "https://ji1kang.github.io"
baseurl: ""
description: Jiwon Kang CV

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Google Scholar"
   link: "https://scholar.google.co.kr/citations?user=3qWZEGkAAAAJ&hl=en"
 - name: "Linkedin"
   link: "https://www.linkedin.com/in/jiwon-kang-7598a3131/"
 - name: "Blog"
   link: "https://velog.io/@ji1kang"
