title: Jiwon Kang
url: "https://ji1kang.github.io"
baseurl: ""
description: Jiwon Kang Online CV

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana/researcher"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Google Scholar"
   link: "https://scholar.google.co.kr/citations?user=3qWZEGkAAAAJ&hl=en"
